"""cambios en los modelos

Revision ID: b9a80f647a4c
Revises: 
Create Date: 2025-05-23 15:23:55.520857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a80f647a4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administratives',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('profile', sa.String(length=1000), nullable=True),
    sa.Column('role', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='school'
    )
    op.create_table('professors',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('profile', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='school'
    )
    op.create_table('students',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('profile', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('enrollment', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='school'
    )
    op.create_table('subjects',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('professor_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['school.professors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='school'
    )
    op.create_table('grades',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('id_student', sa.String(length=100), nullable=False),
    sa.Column('id_subject', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_student'], ['school.students.id'], ),
    sa.ForeignKeyConstraint(['id_subject'], ['school.subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='school'
    )
    op.create_table('student_subjects',
    sa.Column('student_id', sa.String(length=100), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['school.students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['school.subjects.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'subject_id'),
    schema='school'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_subjects', schema='school')
    op.drop_table('grades', schema='school')
    op.drop_table('subjects', schema='school')
    op.drop_table('students', schema='school')
    op.drop_table('professors', schema='school')
    op.drop_table('administratives', schema='school')
    # ### end Alembic commands ###
